# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
baseurl: "/microcast" # the subpath of your site, e.g. /blog
url: "http://soitscometothis.net" # the base hostname & protocol for your site
twitter_username: LK64076007A
github_username:  LK64076007A  

# Add this section to your _config.yml
# You may ignore information you already have
# like title, url and such
#####################################

# Podcast Feed Settings

title:          Driftwood
email:          your-podcast-contact-email
description:    "A short form podcast hosted completely on Github."
subtitle:       "Size isn't everything"
lang:           en-us
author:         Michael
copyright:      "&#x2117; &amp; &#xA9; 2016"


# Outputting
permalink: /:title/

# Build settings
markdown: kramdown
timezone: America/New_York